"""user - add memo

Revision ID: b3c5ae7b083a
Revises: 9a5a9112e100
Create Date: 2024-11-07 11:11:38.465091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c5ae7b083a'
down_revision: Union[str, None] = '9a5a9112e100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('user', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'user')
    # ### end Alembic commands ###
